-- PTO codes were generated by counting existing rows and adding one, then
-- inserted into a UNIQUE column. Two requests submitted in the same moment
-- both read the same count, so the second insert raised a unique violation
-- that nothing caught: the request was lost and the form stayed stuck.
--
-- A sequence hands out each number exactly once regardless of concurrency.
-- The counter no longer restarts each year, so a code identifies a request
-- rather than its position within a year — codes stay unique and ordered,
-- which is all the format is relied on for.
CREATE SEQUENCE IF NOT EXISTS "pto_request_code_seq";
--> statement-breakpoint
-- Start above whatever already exists so no issued code can be repeated.
SELECT setval(
  'pto_request_code_seq',
  GREATEST((SELECT COUNT(*) FROM "pto_requests"), 1)
);
